# This will appear before many messages from the plugin.
message-prefix: '&8[&4WbsArena&8]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'c'

# The highlight colour (to complement the above colour)
highlight-colour: '7'

# Errors will be this colour.
error-colour: '4'

# Error highlights
error-highlight: '7'

options:
  # How should kits be unlocked? Options are:
  # POINT_THRESHOLD (Kits unlock at a certain number of points; if a player drops below a certain number of
  #   points, they lose access to the kit, and are assigned a random one they do have access to.)
  # MONEY_COST (Kits are purchased with the default server currency (requires Vault); once purchased, a permission
  #   is granted)
  # POINT_COST (Kits are purchased with points. Points are consumed to buy the kits.
  #   A permission is granted upon purchase.)
  # PERMISSION_ONLY (Purchasing through the plugin is disabled, and kits are granted based on permissions only.
  #   Kit permissions take the form "wbsarena.kit.owned.[name]".
  kit-unlock-method: POINT_THRESHOLD

  # Should the player be able to pick to randomize their kit?
  # When enabled, the kit selection menu adds an option to randomize their kit,
  # which causes their kit to switch to a random one they have access to every time
  # they join the arena.
  allow-random-kit: true

  # When should player data be saved? Options are:
  # INSTANT (Player data saves as soon as they die, get a kill, or spend points)
  # PERIODIC (Player data is saved intermittently, at a frequency determined by save-frequency (below))
  # DISCONNECT (Player data is saved when a player disconnects, or when leaderboards are recalculated)
  save-method: INSTANT

  # How often (in minutes) should the player data be saved, when save-method is set to periodic?
  save-frequency: 5

  # How old (in minutes) does leaderboard data need to be before refreshing?
  # Note that recalculating refresh rates will automatically save all cached player data before retrieving
  # the leaderboard, regardless of which save-method is used.
  leaderboard-refresh-rate: 2

  # What should the minimum amount of points be?
  # This takes effect when points-per-death is set, if you want to prevent
  # them from going below a certain threshold.
  # Comment out this to remove the lower limit.
  minimum-points: 0

  # Command related options
  commands:
    # How many seconds should "/wbsarena kit preview" last?
    # To disable this feature, and require players to repeat the preview command to
    # end their preview, set this to -1.
    preview-duration: 15
    # The same as above, but when triggered from the preview menu. Cannot be disabled
    # by setting to -1, as a player might preview a kit and then not know how to end it.
    menu-preview-duration: 15

    # Should "/wbsarena kit update" require confirmation to update kits?
    confirm-update-commands: true
    # Should "/wbsarena kit update" use a menu for confirmations?
    # When set to false, the confirmation will require the player to repeat the command.
    menu-confirm-updates: true

    # Should "/wbsarena kit delete" be disabled, so kits can only be deleted
    # by deleting a kit file?
    disable-delete-command: false
    # Should "/wbsarena kit delete" require confirmation to delete kits?
    confirm-delete-commands: true
    # Should "/wbsarena kit delete" use a menu for confirmation?
    # When set to false, the confirmation will require the player to repeat the command.
    menu-confirm-deletion: true


  # Settings that take effect when a player is in an arena.
  arena:
    combat-tagging:

      # How long (in seconds) a player should be considered "in combat" for after taking damage from another
      # player. If the player logs out or leaves the arena while in combat,
      combat-tag-duration: 3

      # Which commands should be disabled while in combat?
      # If allowed-commands is uncommented as well, this will only affect
      # the commands allowed there. For example, if "arena" is allowed,
      # "arena leave" in this list will still block leave without blocking others.
      disabled-commands:
        - arena leave

      # Which commands should be allowed while in combat?
      # Uncommenting this will act as a whitelist, where any command that doesn't
      # start with an element from the list will be blocked.
     # allowed-commands:
     #   - msg
     #   - arena

    # When a player dies, should they be sent to the lobby?
    # When false, players will immediately respawn in the arena, and will need
    # to do "/arena leave" to leave the arena.
    leave-on-death: true

    # The death message that appears when a player dies to another player
    kill-message-format: '%victim% was slain by %attacker%!'
    # The death message that appears when a player dies without being directly killed
    death-message-format: '%victim% died!'

    # How many points should the player get when they get a kill?
    points-per-kill: 2
    # How many points should the player lose when they die?
    points-per-death: 1

    # Non-point related kill rewards that get applied whenever a player gets a kill
    kill-rewards:
      # Items to give the player when they get a kill, in the format "ITEM_TYPE: AMOUNT"
      items:
        # Give 1 golden apple on a kill
        GOLDEN_APPLE: 1

      # Potion effects to apply to the player when they get a kill
      potions:
        SPEED: # The potion effect name
          duration: 3 # How long (in seconds) the potion effect should last
          level: 2 # What level should the effect be?

    # Should projectiles that can't be picked up be despawned after landing?
    # (i.e. Infinity bow arrows, skeleton arrows, drowned tridents)
    despawn-projectiles: true

    # Which commands should be disabled while in the arena?
    # These are always disabled in the arena, but you can disable commands
    # just while in combat above.
    disabled-commands:
      - tpa
      - tpaccept

    # Which commands should be allowed while in combat?
    # Uncommenting this will act as a whitelist, where any command that doesn't
    # start with an element from the list will be blocked.
   # allowed-commands:
   #   - msg
   #   - arena

    # Stop the player from manually dropping items?
    prevent-drops: false

    # Stop the player from taking the provided types of damage?
    # You can see a full list of damage causes here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
    prevent-damage:
      # Prevent fall damage?
      FALL: false
      # Prevent drowning?
      DROWNING: false
      # Missing damage causes will not be prevented.

    # Stop the player from moving items in their inventory?
    prevent-inventory-management: false

    # Should items (including armour) be prevented from taking durability while in the arena?
    prevent-item-damage: true

    # Should projectiles shot by the player be deleted the moment they die or leave the arena?
    delete-projectiles-on-death: false

    # Should tridents thrown by the player be deleted the moment they die or leave the arena?
    # This will always be on if the above option is on, however this can be used to prevent players
    # getting duplicate loyalty tridents after respawning if they get back into the arena quick enough.
    delete-tridents-on-death: true
